define(function(require) {

  var gym = {};

  gym = {
    bench:[
      ['   _      _',
       '  /_\\____/ \\',
       '  \\_/    Y_/',
       '    |    |',
       '    |    |',
       '   ---------------',
       '   ||   ||   || ||',
       '   ||   ||   || ||',
       '   ||        ||',
      ],
      ['      _      _',
       '     /_\\____/ \\',
       '    Y\\_/ Y  \\_/',
       '    |    |',
       '    |    |',
       '   ---------------',
       '   ||   ||   || ||',
       '   ||   ||   || ||',
       '   ||        ||',
      ],
      ['              ',
       '               ',
       '    Y _  Y   _ ',
       '    |/_\\____/ \\',
       '    |\\_/ |  \\_/',
       '   ---------------',
       '   ||   ||   || ||',
       '   ||   ||   || ||',
       '   ||        ||',
      ],
      ['      _      _',
       '     /_\\____/ \\',
       '    Y\\_/ Y  \\_/',
       '    |    |',
       '    |    |',
       '   ---------------',
       '   ||   ||   || ||',
       '   ||   ||   || ||',
       '   ||        ||',
      ],
      ['              ',
       '               ',
       '    Y _  Y   _ ',
       '    |/_\\____/ \\',
       '    |\\_/ |  \\_/',
       '   ---------------',
       
       '   ||   ||   || ||',
       '   ||   ||   || ||',
       '   ||        ||',
      ],
      ['      _      _',
       '     /_\\____/ \\',
       '    Y\\_/ Y  \\_/',
       '    |    |',
       '    |    |',
       '   ---------------',
       '   ||   ||   || ||',
       '   ||   ||   || ||',
       '   ||        ||',
      ],

    ],
    squat: [
      ['         _           _',
       '        / \\_________/_\\',
       '        \\_/Y       Y\\_/',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |'
      ],
      ['    _           _',
       '   / \\_________/_\\',
       '   \\_/     Y   \\_/ Y',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |'
      ],
      ['',
       '',
       '           Y       Y',
       '    _      |    _  |',
       '   / \\_________/_\\ |',
       '   \\_/     |   \\_/ |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
      ],
      ['    _           _',
       '   / \\_________/_\\',
       '   \\_/     Y   \\_/ Y',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |'
      ],
      ['',
       '',
       '           Y       Y',
       '    _      |    _  |',
       '   / \\_________/_\\ |',
       '   \\_/     |   \\_/ |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
      ],
      ['    _           _',
       '   / \\_________/_\\',
       '   \\_/     Y   \\_/ Y',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |',
       '           |       |'
      ]
    ],
    cycle: [
      ['',
       '',
       '          ',
       '          /__\\',
       '          \\__/',
       '   D=>     |',
       '    |      |',
       '    |     / \\',
       '    |\\---/   \\',
       '   /         |',
       '   |   \\     /',
       '   \\____u___/'
      ],
      ['',
       '',
       '          ',
       '          /__\\',
       '          \\__/',
       '   D=>     |',
       '    |      |',
       '    |     / \\',
       '    |\\---/   \\',
       '   /         |',
       '   |  /      /',
       '   \\u_______/'
      ],
      ['',
       '',
       '          ',
       '          /__\\',
       '          \\__/',
       '   D=>     |',
       '    |      |',
       '    |     / \\',
       '    |u---/   \\',
       '   /  \\      |',
       '   |         /',
       '   \\________/'
      ],
      ['',
       '',
       '          ',
       '          /__\\',
       '          \\__/',
       '   D=>     |',
       '    |      |',
       '    |     / \\',
       '    |\\--u/   \\',
       '   /   /     |',
       '   |         /',
       '   \\________/'
      ],

    ],
    swim: [
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
      ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/www>O/owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
      ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwww-O\\owwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
       ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwwwwwwwwwwwww>O/owwwwwwwwwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
       ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww-O\\owwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
      ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo/O&lt;www/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
      ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwo\\O-wwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
       ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwwwwwwwwwwwwwwo/O&lt;wwwwwwwwwwwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
       ],
      ['      ____________________________________________',
       '    T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   T/wwwwwwwo\\O-wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '  T/wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww/',
       '   -------------------------------------------/'
      ]
    ]
  }

  return gym;
});
